### PR TITLE
Improve pluralization rules

### PR DESCRIPTION
**Pull request by ChristosToxiadis**
I made changes based on the conversation in the previous Pull Request. I don't know if i could make those changes in the previous request so to be sure i started a new one. Also it is very strange that the lines 1084-1087 are nested for some reason, while in my IDE the alignment is correct. Can i make a correction in this pull request to fix this or i have to make a new one?

### CODE REVIEW

**Comment by mernst** [comment]
You can and should push changes to your branch, which will automatically appear in the pull request.  (That is what I have been doing; when you open a pull request, that gives maintainers permission to push to your branch.)

The indentation problem was due to the fact that you put tab characters in the source code.  Please [don't do that](https://homes.cs.washington.edu/~mernst/advice/coding-style.html#tabs-vs-spaces).

The title of this new pull request was not informative.  I have fixed it.

I added tests, since all new or changed code should be accompanied by tests.

This looks good now.  Thank you for the improvement!

**Comment by ChristosToxiadis** [comment]
OK thanks for the information and the very helpful advice you gave me! 

I have two more questions. I guess that when you say isEmpty() is more efficient than length(), you mean that is better in terms of time complexity and not in terms of method's logic, right?

 The second question is about GitHub: is it possible to make 2 PRs simultaneously? For example can i make an improvement both in StringPlume and the ArrayPlume? Or they will occur synchronisation problems if both PRs are accepted?

**Comment by mernst** [comment]
> when you say isEmpty() is more efficient than length(), you mean that is better in terms of time complexity and not in terms of method's logic, right?

That is correct.  `isEmpty()` returns as soon as it finds a single character.  `length()` computes the entire string length.  In practice, this is not a big deal.

> The second question is about GitHub: is it possible to make 2 PRs simultaneously? For example can i make an improvement both in StringPlume and the ArrayPlume? Or they will occur synchronisation problems if both PRs are accepted?

Yes, you can make multiple PRs simultaneously.  This is common practice.
You can create multiple branches in your fork, and changes to these branches will not affect one another (unless you explicitly pull one of the branches into the other).  You can create a pull request for each branch

**Comment by ChristosToxiadis** [comment]
Thanks again. Although what you said about isEmpty() makes perfect sense, i was confused while reading this [old article](https://www.java67.com/2014/09/right-way-to-check-if-string-is-empty.html) (2nd paragraph).

**Pull request merged**
