### PR TITLE
Edit dataflow annotations

### PR DESCRIPTION
**Pull request by ChristosToxiadis**

### CODE REVIEW

**Comment by ChristosToxiadis** [comment]
I made a mistake.  I didn't want to make the last commit to this branch. Is there any easy way to undo this?

**Comment by mernst** [comment]
You can run "git revert" which will create a new commit that reverts the last one.
You can also run "git reset" (take care with the many options!) and then force-push, but that is more error-prone.

**Comment by ChristosToxiadis** [comment]
Thanks for the help. Git revert worked perfectly locally but i get this when i am trying to push it:

To https://github.com/ChristosToxiadis/plume-util.git
 ! [rejected]        edit-dataflow-annotations -> edit-dataflow-annotations (non-fast-forward)
error: failed to push some refs to 'https://github.com/ChristosToxiadis/plume-util.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by mernst** [comment]
Did you examine the documentation mentioned in the message that you quoted?
Fixing the problem is usually as simple as `git pull` then `git push`.

**Comment by mernst** [comment]
Where `@SideEffectFree` was not appropriate, I added comments indicating which formal parameters the method modifies.

**Comment by mernst** [comment]
Thanks for these annotations!

**Pull request merged**
